### PR TITLE
string: update spanish translation for European and Latin American users

### PR DESCRIPTION
**Pull request by sguinetti**
This PR serves to update the Spanish language to last master commit. In addition, this PR is for set two types of linguistic variations, one for Spain (Europe) and the other for Latin America. Since one territory uses different formalisms and terms than the other, a new folder was created. This will be very convenient for users.

### CODE REVIEW

**Review by realOxy — APPROVED** [review]

**Review by realOxy — CHANGES_REQUESTED** [review]
Please check the resource directory name is correct.
/home/runner/work/M3UAndroid/M3UAndroid/i18n/src/main/res/values-es-419: Error: Invalid resource directory name

**Comment by realOxy** [comment]
Please check this:

**Comment by sguinetti** [comment]
Yes, I created a new folder. It seems that grade.org does not allow es-419.

**Comment by sguinetti** [comment]
Well, I will have to correct it. I going to edit the es-en and es-419 folders.

**Comment by sguinetti** [comment]
I think the folders for now will be the following:

- es-rMX (for Mexico and by default for other countries) 
- es-ES (only for Spain)

**Comment by realOxy** [comment]
Hmmm, it failed again

**Comment by sguinetti** [comment]
Very strange. So, I will have to revert the es-ES folder renaming again to es-rES.

**Pull request merged**
